server:
  port: 8787
  servlet:
    encoding:
      force-response: true
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinepeople
    username: root
    password: 1234

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: update
    default_batch_fetch_size: 1000
    # 카멜 케이스로 작성 시 스네이크 케이스로 자동으로 변경되게 하기 위한 주석 처리
    #    hibernate.naming.strategy : org.hibernate.cfg.SpringPhysicalNamingStrategy
    #    hibernate.naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${OAUTH_CLIENT_ID}
#            client-secret: ${OAUTH_CLIENT_SECRET}
#            scope:
#              - email
#              - profile

jwt:
  token:
    secret: hello

imp_key: ${imp_key}
imp_secret: ${imp_secret}
