server:
  port: 8787
  servlet:
    encoding:
      force-response: true
      #JSP to Modify Not Restart Server
    jsp:
      init-parameters:
        development: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinepeople
    username: root
    password: 1234
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      max-lifetime: 30000

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate.ddl-auto: update
    default_batch_fetch_size: 1000
    # 카멜 케이스로 작성 시 스네이크 케이스로 자동으로 변경되게 하기 위한 주석 처리
    #    hibernate.naming.strategy : org.hibernate.cfg.SpringPhysicalNamingStrategy
    #    hibernate.naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate.enable_lazy_load_no_trans: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope:
              - email
              - profile

  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}

  #multipart 설정
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

#aws 설정
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR


jwt:
  token:
    secret: hello

imp_key: ${IMP_KEY}
imp_secret: ${IMP_SECRET}


sms:
  key: key
  secret: secret
  phone: phone
